project:
  type: website

website:
  title: "UrbanCoalesce Labs"
  search:
    location: navbar
    type: textbox
  reader-mode: true
  navbar:
    search: true
    background: primary
    right:
      - href: index.qmd
        text: Home
      - href: portfolio.qmd
        text: Portfolio
      - href: explore/index.qmd
        text: Exploration      
        menu:
          - href: https://renjieteo-is415.netlify.app/exercises/thex03.html#overview
            text: HDB Resale Price Prediction comparative analysis with Multiple Linear Regression and Geographically Weighted Random Forest model
          - href: https://spatialbros.netlify.app/
            text: City of Melbourne Spatial Point Analysis (Data Democratisation - user input) 
        
      - icon: github
        href: https://github.com/renj1ete0
      - icon: linkedin
        href: https://www.linkedin.com/in/renjieteo/
  page-footer:
    background: dark
    left: "UC Labs" 
    right: 
      - icon: github
        href: https://github.com/renj1ete0
      - icon: linkedin
        href: https://www.linkedin.com/in/renjieteo/
  #google-analytics: "KEY"
  open-graph: true

format:
  html:
    theme:
      dark: [darkly, dark.scss]
      light: [flatly, light.scss]
    fontsize: 0.98em
    linestretch: 1.7
    toc: true

editor: visual

